# frozen_string_literal: true

# swiftpandas — fast CSV transformation tool with resident-memory daemon
#
# Auto-generated by release.yml in kiraa-ai/kiraa-swift-pandas.
# Do NOT edit url/sha256/version by hand; they are rewritten on every
# release. Tap-specific docs live in this repo's README.
class Swiftpandas < Formula
  desc "Fast CSV transformation tool with resident-memory daemon"
  homepage "https://github.com/kiraa-ai/kiraa-swift-pandas"
  license "Apache-2.0"

  url     "https://github.com/kiraa-ai/kiraa-swift-pandas/releases/download/v0.6.0-beta/swiftpandas-v0.6.0-beta-macos26-universal.zip"
  sha256  "41f34a52e2aab2d8901d48900121ed3271611d13710a7b5090219912293e561f"
  version "0.6.0-beta"

  head "https://github.com/kiraa-ai/kiraa-swift-pandas.git", branch: "main"

  depends_on macos: :ventura
  depends_on xcode: ["15.0", :build] => :head

  def install
    if build.head?
      system "swift", "build", "-c", "release", "--arch", "arm64", "--arch", "x86_64"
      bin.install ".build/apple/Products/Release/swiftpandas"
    else
      bin.install "swiftpandas"
      system "xattr", "-dr", "com.apple.quarantine", bin/"swiftpandas"
    end
  end

  service do
    run [opt_bin/"swiftpandas", "server", "start", "--foreground"]
    keep_alive true
    working_dir var
    log_path        var/"log/swiftpandas.log"
    error_log_path  var/"log/swiftpandas.err"
    environment_variables(
      SWIFTPANDAS_RUNTIME_DIR: var/"swiftpandas",
    )
  end

  test do
    output = shell_output("#{bin}/swiftpandas --help")
    assert_match "swiftpandas", output
    assert_match "server",      output
  end
end
